Repository HanashiDev/dev.hanashi.wsc.faq, pull requests merged in 2022-04, with the labels that each got.

#50 🪲 Bug-Fix
  files/lib/page/FaqQuestionPage.class.php
  package.xml
  requirements/dev.hanashi.wsc.wysiwyg-i18n-form.tar
Labels: bug

#49 Feat/require wcf5 4
  package.xml
Labels: enhancement

#55 sortable question list
  acptemplates/faqQuestionList.tpl
  files/lib/data/faq/QuestionAction.class.php
Labels: enhancement

#63 Update version
  files/acp/database/update_dev.tkirch.wsc.faq_2.0.0.php
  package.xml
Labels: enhancement

#68 Add dependabot
  .github/dependabot.yml
Labels: enhancement

#70 Update readme badges
  README.md
Labels: bug, documentation

#71 Add build workflow
  .github/workflows/build.yml
Labels: enhancement

#73 Remove the "Main" at "Main development" in the readme at Titus
  README.md
Labels: documentation, enhancement

#66 Update package description
  README.md
  package.xml
Labels: enhancement

#75 Set FAQ question list page as parent of FAQ question page
  page.xml
Labels: bug

#77 Execute codestyle workflow on pr
  .github/workflows/codestyle.yml
Labels: bug, enhancement

#79 Fix fatal error when accessing question edit page without ID parameter
  files/lib/acp/form/FaqQuestionEditForm.class.php
Labels: bug

#83 Unify wording
  language/de.xml
  language/en.xml
  page.xml
Labels: enhancement

#81 Update XSD location URLs to 5.4
  aclOption.xml
  acpMenu.xml
  bbcode.xml
  language/de.xml
  language/en.xml
  menuItem.xml
  objectType.xml
  package.xml
  page.xml
  templateListener.xml
  userGroupOption.xml
Labels: enhancement

#61 Improve FAQ question list page layout
  files/style/faq.scss
  templates/__faqQuestionListEntry.tpl
  templates/faqQuestionList.tpl
Labels: enhancement

#87 Do not collapse question when clicking action buttons
  templates/faqQuestionList.tpl
Labels: bug
